version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=db
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs

  frontend:
    build: .
    command: streamlit run frontend/app.py
    ports:
      - "8501:8501"
    environment:
      - MYSQL_HOST=db
    depends_on:
      - api
    volumes:
      - ./logs:/app/logs

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=triangle_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: 